### ISSUE TITLE
Map not working with https

### ISSUE THREAD

**Issue by krav** [hackeriet/hausmania.org#15]

**Comment by stigok** [comment]
Introduced in #9

**Comment by stigok** [comment]
Tiles ligger på fastly

    tile.stamen.com	CNAME	global.prod.fastly.net

og fastly har bare certs til sine egne servere. Vi kan proxye requests selv med nginx. Det blir en ekstra konfigurasjon, men lar seg absolutt gjøre.

Nginx:

```
location /assets/tiles/ {
    proxy_pass http://tile.stamen.com/toner/;
    # TODO: cache requests
    # Q: Pass 'X-Forwarded-For' header?
}
```

Leflet options:

    L.tileLayer('/assets/tiles/{z}/{x}/{y}.png' [...]

**Comment by krav** [comment]
@lassegs De finnes ikke husa et annet sted da?

**Comment by lassegs** [comment]
"f you'd like to display these map tiles on a website that requires HTTPS, use our tile SSL endpoint by replacing http://tile.stamen.com with https://stamen-tiles.a.ssl.fastly.net. Multiple subdomains can be also be used: https://stamen-tiles-{S}.a.ssl.fastly.net. JavaScript can be loaded from https://stamen-maps.a.ssl.fastly.net/js/tile.stamen.js."
the protocol-less URL should be "//stamen-tiles-{S}a.ssl.fastly.net/".
