### ISSUE TITLE
Uploads are broken in admin

### ISSUE THREAD

**Issue by krav** [hackeriet/hausmania.org#16]
Just move to siteleaf?

**Comment by krav** [comment]
But siteleaf breaks facebook (non-)integration :(

**Comment by stigok** [comment]
How does it break facebook?

**Comment by krav** [comment]
In order not to send user data to facebook, data is pulled by cron and html generated, afaik unsupported.

**Comment by krav** [comment]
Solving this by extending jekyll-admin.

**Comment by krav** [comment]
This is important but not actually blocking to publishing the site

**Comment by stigok** [comment]
agree

**Comment by stigok** [comment]
Uploading now works, but having issues with the paths of the resources in preview mode. Issue #68 is taking over this.
