### ISSUE TITLE
Incorporate groups on the front page

### ISSUE THREAD

**Issue by stigok** [hackeriet/hausmania.org#24]
![](https://public.42.fm/1499343475346445832.png)

Since Groups are linking to a different page, what do you think about separating it from the three other links on the same page.

**Comment by krav** [comment]
I agree it's weird, I think a redesign should incorporate groups on the front page with a More link. There's ample space.

Deferring it to a later release though.

**Comment by krav** [comment]
Probably also change the horrid background color

**Comment by krav** [comment]
Needs more input from Haus so we know how it will look with ~70 names on it

**Comment by stigok** [comment]
Related #55
