### ISSUE TITLE
Background on navigation buttons

### ISSUE THREAD

**Issue by stigok** [hackeriet/hausmania.org#25]
![](https://public.42.fm/1499343475346445832.png)

It can some times be hard to see the button text, or maybe even the buttons at all. Thoughts?

**Comment by stigok** [comment]
![](https://public.42.fm/1499343635397399218.png)

**Comment by krav** [comment]
I want the rapid colour cycling thing on hover :) Otherwise make it light gray?

**Comment by krav** [comment]
This is basically #12?

**Comment by stigok** [comment]
Nah. The icon is its own element. Or are you referring to the styling of it?

**Comment by krav** [comment]
It is still the hamburger menu, just expanded? 

Is it possible to add opacity and invert colours to make it always be visible? http://bennettfeely.com/filters/

**Comment by stigok** [comment]
Smart! Yes, mos def. I'm on it
