### ISSUE TITLE
Make scrolling down snap to 1 viewport down?

### ISSUE THREAD

**Issue by krav** [hackeriet/hausmania.org#33]
Background is a bit slow to change otherwise

**Comment by krav** [comment]
https://css-tricks.com/introducing-css-scroll-snap-points/

**Comment by stigok** [comment]
Aldri hørt om snap points i CSS

![](https://public.42.fm/1499355685450921254.png)

Men skal være greit å ordne i javascript. jQuery er allerede inne :+1:

**Comment by krav** [comment]
Or linked polyfill? https://github.com/ckrack/scrollsnap-polyfill
