### ISSUE TITLE
All group images should have the same dimensions

### ISSUE THREAD

**Issue by krav** [hackeriet/hausmania.org#5]

**Comment by stigok** [comment]
I have gone about this the wrong way in the past --- with CSS.

Lets get HQ pictures and hopefully @lassegs can work some imagemagic?

**Comment by krav** [comment]
Meh, worse is better. Users will upload shitty pictures, let them stretch so they can see they need to upload better ones. imagemagick is best run on only trusted content, see: lifetime of vulns.

**Comment by stigok** [comment]
WIth imagemagick, I actually ment @lassegs `s magic skills with images. At least for this first release. The image I uploaded of hackeriet is actually a screenshot of an SVG. Good pictures makes nice design imo.

**Comment by krav** [comment]
I don't want to take responsibility for it, customer will have to deal (once upload is working)
